startService was missing

diff --git a/src/main/scaffolds/polyglot/src/debian/DEBIAN/postinst b/src/main/scaffolds/polyglot/src/debian/DEBIAN/postinst
--- a/src/main/scaffolds/polyglot/src/debian/DEBIAN/postinst
+++ b/src/main/scaffolds/polyglot/src/debian/DEBIAN/postinst
@@ -1,48 +1,54 @@
-${{header}}
-${{control-functions}}
+\${{header}}
+\${{control-functions}}
 
 # Adding system group
-# $1 = group
-# $2 = gid
+# \$1 = group
+# \$2 = gid
 addGroupWithGid() {
-  group="$1"
-  gid="$2"
-  if ! getent group | grep -q "^$group:" ;
+  group="\$1"
+  gid="\$2"
+  if ! getent group | grep -q "^\$group:" ;
   then
-	  echo "Creating system group: $group with gid $gid"
-	  groupadd --system --gid $gid $group
+	  echo "Creating system group: \$group with gid \$gid"
+	  groupadd --system --gid \$gid \$group
   fi
 }
 
 # Adding system user
-# $1 = user
-# $2 = group
-# $3 = description
-# $4 = shell (defaults to /bin/false)
-# $5 = uid
+# \$1 = user
+# \$2 = group
+# \$3 = description
+# \$4 = shell (defaults to /bin/false)
+# \$5 = uid
 addUserWithUid() {
-  user="$1"
-  if [ -z "$user" ]; then
+  user="\$1"
+  if [ -z "\$user" ]; then
 	  echo "usage: addUserWithUid user [group] [description] [shell] [uid]"
 	  exit 1
   fi
-  group=${2:-$user}
-  descr=${3:-No description}
-  shell=${4:-/bin/false}
-  uid=${5}
-  if ! getent passwd | grep -q "^$user:";
+  group=\${2:-$user}
+  descr=\${3:-No description}
+  shell=\${4:-/bin/false}
+  uid=\${5}
+  if ! getent passwd | grep -q "^\$user:";
   then
-	  echo "Creating system user: $user with uid $uid in $group with $descr and shell $shell"
-	  useradd --uid $uid --gid $group --no-create-home --system --shell $shell -c "$descr" $user
+	  echo "Creating system user: \$user with uid \$uid in \$group with \$descr and shell \$shell"
+	  useradd --uid \$uid --gid \$group --no-create-home --system --shell $shell -c "\$descr" $user
   fi
 }
 
-gid=25000
-group="ondkapps"
+group=\${{daemon_group}}
+gid=$gid$
 
-uid=20000
+user=\${{daemon_user}}
+uid=$uid$
 
-addGroupWithGid $group $gid
-addUserWithUid ${{daemon_user}} $group "${{app_name}} daemon-user" ${{daemon_shell}} $uid
 
-${{chown-paths}}
+addGroupWithGid \$group \$gid
+addUserWithUid \$user \$group "\${{app_name}} daemon-user" \${{daemon_shell}} \$uid
+
+\${{chown-paths}}
+
+# delete this for non-service apps
+startService \${{app_name}} || echo "\${{app_name}} could not be registered or started"
+
